"""your message

Revision ID: b7488f896e1c
Revises: 28ebcc812007
Create Date: 2024-07-02 12:36:52.766754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7488f896e1c'
down_revision = '28ebcc812007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
